<span class='tos'><strong>Evil Empire Terms of Service</strong></span><br><hr>

<span class='author'><strong>Please take a moment to review the rules and conditions detailed below.</strong><br><br>

        <span class='tos'><strong>Restriction of Access</strong></span><br>
        <span class='tos'>In this segment "Officialy Restricted" means/includes ESTsoft Corp., ESTsoft Inc., NBird LLC, NBird, SDO, SNDO and SNDA.
        No one from Officialy Restricted, associated with Officialy Restricted or any such affiliated company or anyone directed by Officialy Restricted or its related companies is permitted to enter these web sites or view any content contained within these sites at any time what so ever due to controversial reasons.</span>
    <br><br><span class='tos'><strong>Acceptance of Terms of Service</strong></span><br>
        <span class='tos'>Each time you use or cause access to this web site or services, you agree to be bound by these Terms of Service, and as amended from time to time with or without notice to you. In addition, if you are using a particular service on or through this web site, you will be subject to any rules or guidelines applicable to those services and they shall be incorporated by reference into these Terms of Service.
        Evil Empire Cabal (evilempire.website) reserves the right to modify these Terms of Service at any time, without notice.</span>
    <br><br><span class='tos'><strong>Our Service</strong></span><br>
        <span class='tos'>Our web sites and services provided to you on and through our web site on an AS IS basis. You agree that the owners of this web site exclusively reserve the right and may, at any time and without notice and any liability to you, modify or discontinue this web site and its services or delete the data you provide, whether temporarily or permanently. We shall have no responsibility or liability for the timeliness, deletion, failure to store, inaccuracy, or improper delivery of any data or information.
        Evil Empire Cabal (evilempire.website) reserves the right to interrupt the Service from time to time on a regularly scheduled basis or otherwise with or without prior notice in order to perform maintenance.
        <br>You acknowledge that the Service may be interrupted for reasons beyond the control of Evil Empire Cabal (evilempire.website), and Evil Empire Cabal (evilempire.website) cannot guarantee that you will be able to access the Service whenever you may wish to do so. Evil Empire Cabal (evilempire.website) shall not be liable for any interruption of the Service, delay or failure to perform resulting from any causes beyond its reasonable control.</span>
    <br><br><span class='tos'><strong>Your Responsibilities and Registration Obligations</strong></span><br>
        <span class='tos'>In order to use ur web sites and services, you must register first, and agree to provide truthful information when requested.</span>
    <br><br><span class='tos'><strong>Account</strong></span><br>
        <span class='tos'>During the registration process, you will be required to select a user name and a password that are specific to the Account (collectively known as the "Password"). Your Password is to be kept confidential at all times and you are solely responsible for the security of your Password. You may not disclose your Password to anyone, or allow your Password to be used by anyone other than yourself and/or your one minor child. Evil Empire Cabal (evilempire.website) is not responsible for any harm that may result to the Account (including without limitation the deletion or modification of characters in the Account) as a result of a lost or shared password. The user name you choose shall be subject to the naming guidelines contained in this Agreement. Evil Empire Cabal (evilempire.website) is not responsible in the event that the Account is "hacked," or if the Account or your computer is damaged by a virus, or for any other issues with your computer or the Account. If you think that the Account has been compromised, please contact Evil Empire Cabal (evilempire.website) Technical Support, either through our GM or Help Desk support system.
        <br>Donations are NOT required to use our Service, but note that users who Donate receive gifts based on the proportion of their contribution. You agree that users who contribute deserve to receive gifts, because Donations help keep the Community alive and you agree to be part of the Community by using our Web Sites and/or Service.
        <br>You hereby agree to Donate, though Evil Empire Cabal (evilempire.website), in its sole and absolute discretion, can suspend or terminate your access to the Service and disable or delete the Account if you violate any terms from our Agreement. Also Evil Empire Cabal (evilempire.website) its not responsible for Donation issues caused by either Paypal Company, PSC Company, Western Union, Bank Company or Moneybookers Company.
        <br>Evil Empire Cabal (evilempire.website) does not recognize the transfer of Accounts, and will result in the permanent banning of the Account. You may not offer any Account for sale or trade, and any such offer is a violation of this Agreement and may result in suspension or termination of the Account.
        <br>There are no refunds where the Account is terminated/banned.</span>
    <br><br><span class='tos'><strong>Your Conduct</strong></span><br>
        <span class='tos'>You agree that all information or data of any kind, whether text, software, code, music or sound, photographs or graphics, video or other materials (Content), publicly or privately provided, shall be the sole responsibility of the person providing the Content or the person whose user account is used. You agree that our web site may expose you to Content that may be objectionable or offensive. We shall not be responsible to you in any way for the Content that appears on this web site nor for any error or omission. You explicitly agree, in using this web site or any service provided, that you shall not:
            <br>Provide any Content or perform any conduct that may be threatening, harmful, abusive, harassing, stalking, tortuous, defamatory, libelous, vulgar, obscene, offensive, objectionable, pornographic, designed to or does interfere or interrupt this web site or any service provided, infected with a virus or other destructive or deleterious programming routine, give rise to civil or criminal liability, or which may violate an applicable local, national or international law;
            <br>Impersonate or misrepresent your association with any person or entity, or forge or otherwise seek to conceal or misrepresent the origin of any Content provided by you;
            <br>Collect or harvest any data about other users;
            <br>Provide or use this web site and any Content or service in any commercial manner or in any manner that would involve junk mail, spam, chain letters, pyramid schemes, or any other form of unauthorized advertising without our prior written consent.
        <br>In particular, you may not use any name:
            Belonging to another person with the intent to impersonate that person, including, without limitation, an agent of Evil Empire Cabal (evilempire.website);
            Belonging to any religious figure or deity;
            Subject to the rights of any other person or entity without written authorization from that person or entity;
            That belongs to a popular culture figure, celebrity, or media personality;
            That is, contains, or is substantially similar to a trademark or game mark, whether registered or not;
            Related to drugs, sex, alcohol, or criminal activity;
            That incorporates 'swear' words or which are otherwise offensive, defamatory, vulgar, obscene, hateful, or racially, ethnically or otherwise objectionable;
            Comprised of partial or complete sentence;
            Comprised of gibberish.
        <br>You may not use a misspelling or an alternative spelling to circumvent the name restrictions listed above, nor can you have a "first" and "last" name that, when combined, violate the above name restrictions.
        <br>Evil Empire Cabal (evilempire.website) may, in its sole and absolute discretion, take whatever action it deems necessary to preserve the integrity of Services. Violation of any of the terms and conditions set forth above may result in actions being taken by Evil Empire Cabal (evilempire.website), effective immediately or at a time determined by Evil Empire Cabal (evilempire.website), which may include without limitation: temporarily suspending your access to our Service, or permanently terminating your access to our Service. Without limiting the foregoing, Evil Empire Cabal (evilempire.website) retains the right to decline Services to any user who violates the Agreement.</span>
    <br><br><span class='tos'><strong>Submission of Content on this Web Site</strong></span><br>
        <span class='tos'>By providing any Content to our web site:
            <br>You agree to grant to us a worldwide, royalty-free, perpetual, non-exclusive right and license (including any moral rights or other necessary rights) to use, display, reproduce, modify, adapt, publish, distribute, perform, promote, archive, translate, and to create derivative works and compilations, in whole or in part. Such license will apply with respect to any form, media, technology known or later developed;
            <br>You warrant and represent that you have all legal, moral, and other rights that may be necessary to grant us with the license set forth in this segment;
            <br>You acknowledge and agree that we shall have the right (but not obligation), in our sole discretion, to refuse to publish or to remove or block access to any Content you provide at any time and for any reason, with or without notice.</span>
    <br><br><span class='tos'><strong>Third Party Services</strong></span><br>
        <span class='tos'>Goods and services of third parties may be advertised and/or made available on or through this web site. Representations made regarding products and services provided by third parties are governed by the policies and representations made by these third parties. We shall not be liable for or responsible in any manner for any of your dealings or interaction with third parties.</span>
    <br><br><span class='tos'><strong>Indemnification</strong></span><br>
        <span class='tos'>You agree to indemnify and hold us harmless, our subsidiaries, affiliates, related parties, officers, directors, employees, agents, independent contractors, advertisers, partners, and co-branders from any claim or demand, including reasonable attorney's fees, that may be made by any third party, that is due to or arising out of your conduct or connection with this web site or service, your provision of Content, your violation of this Terms of Service or any other violation of the rights of another person or party.</span>
    <br><br><span class='tos'><strong>DISCLAIMER OF WARRANTIES</strong></span><br>
        <span class='tos'>YOU UNDERSTAND AND AGREE THAT YOUR USE OF THIS WEB SITE AND ANY SERVICES OR CONTENT PROVIDED (THE SERVICE) IS MADE AVAILABLE AND PROVIDED TO YOU AT YOUR OWN RISK. IT IS PROVIDED TO YOU AS IS AND WE EXPRESSLY DISCLAIM ALL WARRANTIES OF ANY KIND, IMPLIED OR EXPRESS, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT. WE MAKE NO WARRANTY, IMPLIED OR EXPRESS, THAT ANY PART OF THE SERVICE WILL BE UNINTERRUPTED, ERROR-FREE, VIRUS-FREE, TIMELY, SECURE, ACCURATE, RELIABLE, OF ANY QUALITY, NOR THAT ANY CONTENT IS SAFE IN ANY MANNER FOR DOWNLOAD. YOU UNDERSTAND AND AGREE THAT NEITHER US NOR ANY PARTICIPANT IN THE SERVICE PROVIDES PROFESSIONAL ADVICE OF ANY KIND AND THAT USE OF SUCH ADVICE OR ANY OTHER INFORMATION IS SOLELY AT YOUR OWN RISK AND WITHOUT OUR LIABILITY OF ANY KIND. Some jurisdictions may not allow disclaimers of implied warranties and the above disclaimer may not apply to you only as it relates to implied warranties.</span>
    <br><br><span class='tos'><strong>LIMITATION OF LIABILITY</strong></span><br>
        <span class='tos'>YOU EXPRESSLY UNDERSTAND AND AGREE THAT WE SHALL NOT BE LIABLE FOR ANY DIRECT, INDIRECT, SPECIAL, INCIDENTAL, CONSEQUENTIAL OR EXEMPLARY DAMAGES, INCLUDING BUT NOT LIMITED TO, DAMAGES FOR LOSS OF PROFITS, GOODWILL, USE, DATA OR OTHER INTANGIBLE LOSS (EVEN IF WE HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES), RESULTING FROM OR ARISING OUT OF:
            <br>THE USE OF OR THE INABILITY TO USE THE SERVICE;
            <br>THE COST TO OBTAIN SUBSTITUTE GOODS AND/OR SERVICES RESULTING FROM ANY TRANSACTION ENTERED INTO ON THROUGH THE SERVICE;
            <br>UNAUTHORIZED ACCESS TO OR ALTERATION OF YOUR DATA TRANSMISSIONS;
            <br>STATEMENTS OR CONDUCT OF ANY THIRD PARTY ON THE SERVICE;
            <br>ANY OTHER MATTER RELATING TO THE SERVICE.
        <br>Please remember that we are not responsible for any messages posted. We do not vouch for or warrant the accuracy, completeness or usefulness of any message, and are not responsible for the contents of any message. We have the ability to remove objectionable messages and we will make every effort to do so, within a reasonable time frame, if we determine that removal is necessary. You agree not to post any copyrighted material unless the copyright is owned by you.</span>

        <br><br><hr><br><span class='tos'>If you have read, understood and agree to these rules and conditions, you may use our Web Sites and Service.</span>
